---
- name: Install packages
  apt: name={{item}} state=installed
  sudo: yes
  with_items:
    - xvfb

- name: Copy service file
  copy: >
    src=etc/systemd/system/xvfb.service
    dest=/etc/systemd/system/xvfb.service
    mode=0644
  sudo: yes

- name: Start xvfb service
  systemd: name=xvfb state=started enabled=yes
  sudo: yes

- name: Export DISPLAY
  lineinfile: >
    dest=~/.profile
    state=present
    line="export DISPLAY=:99"
