---
- name: Add Java repository
  sudo: yes
  apt_repository: repo="ppa:webupd8team/java"

- name: Accept Java License
  shell: >
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Install Java
  sudo: yes
  apt: name=oracle-java7-installer state=latest
